apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytomcat-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selctor:
    matchLabels:
      app: tomcat-frontend
  template:
    metadata:
      name: tomcatpod
      labels:
        app: tomcat-frontend
    spec:
      containers:
        - name: tomcat
          imagePullPolicy: Always
          image: shailbrox/tomcat:v1
          ports: 
           - containerPort: 8080

